<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SAQHFHE" failures="0" tests="5" name="com.testNGRA.TC_001_GET_Request" time="0.024" errors="1" timestamp="2023-03-24T12:00:03 IST" skipped="4">
  <testcase classname="com.testNGRA.TC_001_GET_Request" name="checkServerType" time="0.001">
    <skipped/>
  </testcase> <!-- checkServerType -->
  <system-out/>
  <testcase classname="com.testNGRA.TC_001_GET_Request" name="getAllEmp" time="0.022">
    <error message="Cannot invoke &quot;org.apache.log4j.Logger.info(Object)&quot; because &quot;this.logger&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.log4j.Logger.info(Object)" because "this.logger" is null
at com.testNGRA.TC_001_GET_Request.getAllEmp(TC_001_GET_Request.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getAllEmp -->
  <system-out/>
  <testcase classname="com.testNGRA.TC_001_GET_Request" name="checkContentType" time="0.000">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <system-out/>
  <testcase classname="com.testNGRA.TC_001_GET_Request" name="checkStatusCode" time="0.000">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <system-out/>
  <testcase classname="com.testNGRA.TC_001_GET_Request" name="checkStatusLine" time="0.001">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
  <system-out/>
</testsuite> <!-- com.testNGRA.TC_001_GET_Request -->
